import {
  TimelineDayId,
  DayForecastPoint,
  HistoricalDataPoint,
  HospitalNode,
  DigitalTwinZoneData,
  DiseaseModelConfig
} from './types';

export const HISTORICAL_PATIENT_DATA: HistoricalDataPoint[] = [
  { date: 'Aug 24', admissions: 342, occupancyPercent: 68 },
  { date: 'Aug 25', admissions: 348, occupancyPercent: 70 },
  { date: 'Aug 26', admissions: 355, occupancyPercent: 71 },
  { date: 'Aug 27', admissions: 362, occupancyPercent: 72 },
  { date: 'Aug 28', admissions: 359, occupancyPercent: 72 },
  { date: 'Aug 29', admissions: 368, occupancyPercent: 74 },
  { date: 'Aug 30', admissions: 374, occupancyPercent: 75 },
  { date: 'Aug 31', admissions: 381, occupancyPercent: 76 },
  { date: 'Sep 01', admissions: 378, occupancyPercent: 75 },
  { date: 'Sep 02', admissions: 385, occupancyPercent: 77 },
  { date: 'Sep 03', admissions: 390, occupancyPercent: 78 },
  { date: 'Sep 04', admissions: 392, occupancyPercent: 78 },
];

export const TIMELINE_FORECAST_MAP: Record<TimelineDayId, DayForecastPoint> = {
  NOW: {
    dayId: 'NOW',
    label: 'TODAY (T+0)',
    dayOffset: 0,
    dateString: 'Sep 06 (Today)',
    isBreach: false,
    totalOccupancyPercent: 78,
    totalAdmittedPatients: 392,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 386, upperBound: 398 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 43,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 84,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 18,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 68,
        daysRemaining: 6.2,
        burnRateLitersPerMin: 412,
        risk: 'STABLE',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 64,
      staffOnDutyRatio: '1:4',
      activeIsolationPatients: 14,
    },
  },
  MON: {
    dayId: 'MON',
    label: 'MON (T+1)',
    dayOffset: 1,
    dateString: 'Sep 07',
    isBreach: false,
    totalOccupancyPercent: 81,
    totalAdmittedPatients: 405,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 396, upperBound: 416 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 45,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 86,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 19,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 64,
        daysRemaining: 5.4,
        burnRateLitersPerMin: 435,
        risk: 'STABLE',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 70,
      staffOnDutyRatio: '1:4',
      activeIsolationPatients: 17,
    },
  },
  TUE: {
    dayId: 'TUE',
    label: 'TUE (T+2)',
    dayOffset: 2,
    dateString: 'Sep 08',
    isBreach: false,
    totalOccupancyPercent: 84,
    totalAdmittedPatients: 420,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 408, upperBound: 432 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 48,
        shortageDelta: 0,
        risk: 'WATCH',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 89,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 20,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 58,
        daysRemaining: 4.6,
        burnRateLitersPerMin: 460,
        risk: 'WATCH',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 76,
      staffOnDutyRatio: '1:5',
      activeIsolationPatients: 21,
    },
  },
  WED: {
    dayId: 'WED',
    label: 'WED (T+3)',
    dayOffset: 3,
    dateString: 'Sep 09',
    isBreach: false,
    totalOccupancyPercent: 86,
    totalAdmittedPatients: 438,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 422, upperBound: 454 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 50,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 92,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 21,
        shortageDelta: 1,
        risk: 'HIGH',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 51,
        daysRemaining: 3.8,
        burnRateLitersPerMin: 488,
        risk: 'WATCH',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 82,
      staffOnDutyRatio: '1:5',
      activeIsolationPatients: 26,
    },
  },
  THU: {
    dayId: 'THU',
    label: 'THU (T+4)',
    dayOffset: 4,
    dateString: 'Sep 10',
    isBreach: true,
    totalOccupancyPercent: 91,
    totalAdmittedPatients: 462,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 444, upperBound: 480 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 54,
        shortageDelta: 4,
        risk: 'CRITICAL',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 95,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 22,
        shortageDelta: 2,
        risk: 'CRITICAL',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 42,
        daysRemaining: 2.9,
        burnRateLitersPerMin: 520,
        risk: 'HIGH',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 89,
      staffOnDutyRatio: '1:6',
      activeIsolationPatients: 31,
    },
  },
  FRI: {
    dayId: 'FRI',
    label: 'FRI (T+5 - PEAK BREACH)',
    dayOffset: 5,
    dateString: 'Sep 11 (Breach Forecast)',
    isBreach: true,
    totalOccupancyPercent: 94,
    totalAdmittedPatients: 486,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 465, upperBound: 508 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 59,
        shortageDelta: 9, // +9 ICU Bed Shortage
        risk: 'CRITICAL',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 96,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 24,
        shortageDelta: 4, // +4 Ventilator Shortage
        risk: 'CRITICAL',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 32,
        daysRemaining: 2.1,
        burnRateLitersPerMin: 565,
        risk: 'CRITICAL',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 96,
      staffOnDutyRatio: '1:7',
      activeIsolationPatients: 38,
    },
  },
  SAT: {
    dayId: 'SAT',
    label: 'SAT (T+6)',
    dayOffset: 6,
    dateString: 'Sep 12',
    isBreach: true,
    totalOccupancyPercent: 97,
    totalAdmittedPatients: 508,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 482, upperBound: 532 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 63,
        shortageDelta: 13,
        risk: 'CRITICAL',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 98,
        shortageDelta: 0,
        risk: 'HIGH',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 25,
        shortageDelta: 5,
        risk: 'CRITICAL',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 23,
        daysRemaining: 1.4,
        burnRateLitersPerMin: 590,
        risk: 'CRITICAL',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 99,
      staffOnDutyRatio: '1:8',
      activeIsolationPatients: 44,
    },
  },
  SUN: {
    dayId: 'SUN',
    label: 'SUN (T+7)',
    dayOffset: 7,
    dateString: 'Sep 13',
    isBreach: true,
    totalOccupancyPercent: 99,
    totalAdmittedPatients: 524,
    capacityThreshold: 500,
    confidenceInterval: { lowerBound: 495, upperBound: 550 },
    resources: {
      icu: {
        currentCapacity: 41,
        totalCapacity: 50,
        projectedDemand: 66,
        shortageDelta: 16,
        risk: 'CRITICAL',
      },
      generalBeds: {
        currentCapacity: 82,
        totalCapacity: 100,
        projectedDemand: 100,
        shortageDelta: 0,
        risk: 'CRITICAL',
      },
      ventilators: {
        currentCapacity: 18,
        totalCapacity: 20,
        projectedDemand: 26,
        shortageDelta: 6,
        risk: 'CRITICAL',
      },
      oxygen: {
        currentPercentage: 71,
        projectedPercentage: 14,
        daysRemaining: 0.8,
        burnRateLitersPerMin: 620,
        risk: 'CRITICAL',
      },
    },
    hospitalState: {
      emergencyTriagePressure: 100,
      staffOnDutyRatio: '1:8',
      activeIsolationPatients: 49,
    },
  },
};

export const TIMELINE_KEYS: TimelineDayId[] = ['NOW', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];

export const REGIONAL_HOSPITAL_NODES: HospitalNode[] = [
  {
    id: 'origin-bhopal-dist',
    name: 'BHOPAL DISTRICT HOSPITAL',
    code: 'BPL-DIST-01',
    facilityType: 'District Tertiary Center',
    distanceKm: 0,
    transitTimeMinutes: 0,
    availableIcuBeds: 9, // 50 - 41
    totalIcuBeds: 50,
    availableGeneralBeds: 18,
    availableVentilators: 2,
    compatibilityScore: 100,
    badge: 'Origin Facility',
    isCurrent: true,
    status: 'CRITICAL_SOURCE',
    coordinates: { x: 50, y: 52 },
  },
  {
    id: 'hosp-a-aiims',
    name: 'HOSPITAL A — AIIMS BHOPAL',
    code: 'AIIMS-BPL-02',
    facilityType: 'National Apex Medical Center',
    distanceKm: 8.2,
    transitTimeMinutes: 14,
    availableIcuBeds: 24,
    totalIcuBeds: 90,
    availableGeneralBeds: 62,
    availableVentilators: 16,
    compatibilityScore: 98,
    badge: 'Best Proximity',
    isCurrent: false,
    status: 'OPTIMAL',
    coordinates: { x: 74, y: 32 },
  },
  {
    id: 'hosp-b-hamidia',
    name: 'HOSPITAL B — HAMIDIA HOSPITAL',
    code: 'HAMIDIA-BPL-03',
    facilityType: 'Associated GMC Teaching Hospital',
    distanceKm: 11.4,
    transitTimeMinutes: 21,
    availableIcuBeds: 18,
    totalIcuBeds: 65,
    availableGeneralBeds: 44,
    availableVentilators: 11,
    compatibilityScore: 94,
    badge: 'High Compatibility',
    isCurrent: false,
    status: 'OPTIMAL',
    coordinates: { x: 32, y: 28 },
  },
  {
    id: 'hosp-c-bmhrc',
    name: 'HOSPITAL C — BMHRC RESEARCH CENTRE',
    code: 'BMHRC-BPL-04',
    facilityType: 'Super-Specialty Pulmonary Institute',
    distanceKm: 15.1,
    transitTimeMinutes: 28,
    availableIcuBeds: 7,
    totalIcuBeds: 35,
    availableGeneralBeds: 22,
    availableVentilators: 8,
    compatibilityScore: 91,
    badge: 'Specialized Pulmonary',
    isCurrent: false,
    status: 'ACCEPTING',
    coordinates: { x: 68, y: 78 },
  },
  {
    id: 'hosp-d-chirayu',
    name: 'HOSPITAL D — CHIRAYU MEDICAL COLLEGE',
    code: 'CHIRAYU-BPL-05',
    facilityType: 'Regional Medical Campus Reserve',
    distanceKm: 19.3,
    transitTimeMinutes: 34,
    availableIcuBeds: 32,
    totalIcuBeds: 110,
    availableGeneralBeds: 85,
    availableVentilators: 22,
    compatibilityScore: 89,
    badge: 'Regional Reserve',
    isCurrent: false,
    status: 'OPTIMAL',
    coordinates: { x: 22, y: 74 },
  },
];

export const DISEASE_MODELS: DiseaseModelConfig[] = [
  {
    id: 'covid-19',
    name: 'SARS-CoV-2 (COVID-19)',
    strain: 'Omicron Sublineage JN.1',
    status: 'Active',
    rt: 1.34,
    caseTrend7dPercent: 12.4,
    transmissionTrend: 'Increasing',
    hospitalAdmissionRate: 4.8,
    icuAdmissionRate: 1.6,
    forecastHorizonDays: 7,
    description: 'Ensemble Bayesian Neural Network integrating regional wastewater telemetry, genomic sequencing, and outpatient influenza-like illness (ILI) velocity across Bhopal municipal wards.',
  },
  {
    id: 'influenza-a',
    name: 'Influenza A',
    strain: 'H1N1 Seasonal Variant',
    status: 'Calibrating',
    rt: 1.18,
    caseTrend7dPercent: 6.2,
    transmissionTrend: 'Increasing',
    hospitalAdmissionRate: 3.1,
    icuAdmissionRate: 0.9,
    forecastHorizonDays: 7,
    description: 'Epidemiological compartmental model tuned to secondary respiratory distress and pediatric inpatient surges.',
  },
  {
    id: 'dengue-serotype2',
    name: 'Dengue Serotype 2',
    strain: 'DENV-2 Cosmopolitan',
    status: 'Monitoring',
    rt: 1.42,
    caseTrend7dPercent: 18.9,
    transmissionTrend: 'Increasing',
    hospitalAdmissionRate: 6.4,
    icuAdmissionRate: 2.1,
    forecastHorizonDays: 7,
    description: 'Vector-density spatial model with precipitation lag markers tracking platelet supply and emergency triage pressure.',
  },
  {
    id: 'respiratory-syncytial',
    name: 'Respiratory Syncytial Virus (RSV)',
    strain: 'Lineage RSV-A',
    status: 'Active',
    rt: 1.09,
    caseTrend7dPercent: 3.8,
    transmissionTrend: 'Plateau',
    hospitalAdmissionRate: 2.7,
    icuAdmissionRate: 0.7,
    forecastHorizonDays: 7,
    description: 'Pediatric and geriatric vulnerability trajectory index cross-referenced with regional nursery and senior care facility admissions.',
  },
];

export const DIGITAL_TWIN_BASE_ZONES: DigitalTwinZoneData[] = [
  {
    id: 'icu',
    name: 'INTENSIVE CARE UNIT (ICU)',
    floor: 'LEVEL 03 — NORTH TOWER',
    currentOccupancy: 41,
    maxCapacity: 50,
    utilizationRate: 82,
    risk: 'WATCH',
    metricLabel: 'SURGE BUFFER',
    metricValue: '9 BEDS REMAINING',
    telemetry: {
      temperature: '21.2°C',
      staffRatio: '1:2 NURSE-BED',
      flowState: 'NEGATIVE PRESSURE STABLE',
    },
  },
  {
    id: 'emergency',
    name: 'EMERGENCY & TRAUMA BAY',
    floor: 'GROUND LEVEL — RAPID ACCESS',
    currentOccupancy: 28,
    maxCapacity: 35,
    utilizationRate: 80,
    risk: 'WATCH',
    metricLabel: 'TRIAGE QUEUE',
    metricValue: '6 ACTIVE CODE YELLOW',
    telemetry: {
      temperature: '22.0°C',
      staffRatio: '1:3 RESIDENT-BAY',
      flowState: 'AMBULANCE BAY 3/4 ACTIVE',
    },
  },
  {
    id: 'general_wards',
    name: 'GENERAL INPATIENT WARDS',
    floor: 'LEVEL 02 — WINGS A & B',
    currentOccupancy: 82,
    maxCapacity: 100,
    utilizationRate: 82,
    risk: 'WATCH',
    metricLabel: 'BED TURNOVER',
    metricValue: '14 DISCHARGES TODAY',
    telemetry: {
      temperature: '23.1°C',
      staffRatio: '1:6 NURSE-PATIENT',
      flowState: 'WING B AT 88% OCCUPANCY',
    },
  },
  {
    id: 'isolation',
    name: 'AIRBORNE INFECTION ISOLATION',
    floor: 'LEVEL 03 — SOUTH POD',
    currentOccupancy: 14,
    maxCapacity: 20,
    utilizationRate: 70,
    risk: 'WATCH',
    metricLabel: 'BIO-CONTAINMENT',
    metricValue: 'HEPA 99.97% FILTRATION',
    telemetry: {
      temperature: '20.5°C',
      staffRatio: '1:2 LEVEL-3 PPE',
      flowState: 'DELTA PRESSURE -12.4 Pa',
    },
  },
  {
    id: 'oxygen_substation',
    name: 'CRYOGENIC OXYGEN SUBSTATION',
    floor: 'FACILITY BASEMENT & EXTERNAL YARD',
    currentOccupancy: 71,
    maxCapacity: 100,
    utilizationRate: 71,
    risk: 'STABLE',
    metricLabel: 'MAIN BULK TANK',
    metricValue: '7,100 L / 10,000 L',
    telemetry: {
      temperature: '-183.0°C',
      staffRatio: 'AUTOMATED MONITORED',
      flowState: 'LINE PRESSURE 4.2 BAR',
    },
  },
  {
    id: 'ventilator_storage',
    name: 'BIOMEDICAL VENTILATOR DEPOT',
    floor: 'LEVEL 01 — EQUIPMENT RESERVE',
    currentOccupancy: 18,
    maxCapacity: 20,
    utilizationRate: 90,
    risk: 'HIGH',
    metricLabel: 'MOBILE UNITS READY',
    metricValue: '2 STERILIZED RESERVES',
    telemetry: {
      temperature: '21.0°C',
      staffRatio: 'BIOMED TECH ON SITE',
      flowState: 'CALIBRATION VALID',
    },
  },
  {
    id: 'pharmacy',
    name: 'CENTRAL STERILE PHARMACY',
    floor: 'GROUND LEVEL — CORE DEPOT',
    currentOccupancy: 86,
    maxCapacity: 100,
    utilizationRate: 86,
    risk: 'STABLE',
    metricLabel: 'CRITICAL ANTIVIRALS',
    metricValue: '18 DAYS INVENTORY',
    telemetry: {
      temperature: '4.0°C (COLD CHAIN)',
      staffRatio: 'PHARMACISTS ON SHIFT: 4',
      flowState: 'RESTOCK EN ROUTE (24H)',
    },
  },
];
